create table countries (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    COUNTRY varchar(100) not null,
    PRIMARY KEY (ID),
    UNIQUE (COUNTRY)
);

create table address (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    ADDRESS varchar(100) not null,
    CITY varchar(100) not null,
    COUNTRY_ID int not null,
    ZIP_CODE varchar(10) not null,
    PRIMARY KEY (ID),
    CONSTRAINT ADDRESS_COUNTRY_FK FOREIGN KEY (COUNTRY_ID) REFERENCES countries(ID)
);


create table staff (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME varchar(100) not null,
    LAST_NAME varchar(100) not null,
    ADDRESS_ID int,
    BIRTH_DATE date,
    HIRE_DATE date not null,
    TERMINATION_DATE date,
    SALARY float,
    DISABLED boolean default false not null,
    STAFF_ID int,
    PRIMARY KEY (ID),
    CONSTRAINT STAFF_ADDRESS_FK FOREIGN KEY (STAFF_ID) REFERENCES address(ID),
    CONSTRAINT STAFF_HIERARCHY_FK FOREIGN KEY (STAFF_ID) REFERENCES staff(ID)
);

create table clients (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    FIRST_NAME varchar(100) not null,
    LAST_NAME varchar(100) not null,
    ADDRESS_ID int not null,
    CREATE_DATE date not null,
    PRIMARY KEY (ID),
    CONSTRAINT CLIENT_ADDRESS_FK FOREIGN KEY (ADDRESS_ID) REFERENCES address(ID)
);

create table products (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    NAME varchar(100) not null,
    DESCRIPTION varchar(256),
    PRICE float not null,
    NO_ITEMS int,
    RESTOCK_DATE date,
    --Region comma separated list
    AVAILABLE_REGIONS varchar(256),
    PRIMARY KEY (ID)
);

create table reviewClientProduct (
    ID int GENERATED BY DEFAULT AS IDENTITY,
    CLIENT_ID int not null,
    PRODUCT_ID int not null,
    DESCRIPTION varchar(256) not null,
    RATING int,
    PRIMARY KEY (ID),
    CONSTRAINT RVW_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES clients(ID),
    CONSTRAINT RVW_PRODUCT_FK FOREIGN KEY (PRODUCT_ID) REFERENCES products(ID)
);

--We're using bigint here. Can be mapped to java.lang.Long
create table orders (
    ID bigint GENERATED BY DEFAULT AS IDENTITY,
    CLIENT_ID int not null,
    ORDER_DATE date,
    ORDER_STATUS varchar(24),
    BILLING_ADDRESS varchar(128) not null,
    PRIMARY KEY (ID),
    CONSTRAINT ORDER_CLIENT_FK FOREIGN KEY (CLIENT_ID) REFERENCES clients(ID)
);

create table ordersDetails (
    ID bigint GENERATED BY DEFAULT AS IDENTITY,
    ORDER_ID int not null,
    PRODUCT_ID int not null,
    QUANTITY int not null,
    PRIMARY KEY (ID),
    CONSTRAINT ORDDETAIL_ORDER_FK FOREIGN KEY (ORDER_ID) REFERENCES orders(ID)
)

